imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_doctrine_orm_admin.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_notification.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

    form_themes:
        - 'ApplicationSonataMediaBundle:Form:media_widgets.html.twig'
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType


    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
              default:
#                  metadata_cache_driver: apcu
#                  query_cache_driver: apcu
#                  result_cache_driver: apcu
                  naming_strategy: doctrine.orm.naming_strategy.underscore
                  auto_mapping: true
                  mappings:
                        ApplicationSonataNotificationBundle: ~
                        ApplicationSonataMediaBundle: ~
                        SonataMediaBundle: ~
                        ApplicationSonataClassificationBundle: ~
                        SonataClassificationBundle: ~
                        gedmo_translatable:
                            type: annotation
                            prefix: Gedmo\Translatable\Entity
                            dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                            alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                            is_bundle: false
                        gedmo_translator:
                            type: annotation
                            prefix: Gedmo\Translator\Entity
                            dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                            alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                            is_bundle: false
                        gedmo_loggable:
                            type: annotation
                            prefix: Gedmo\Loggable\Entity
                            dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                            alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                            is_bundle: false
                        gedmo_tree:
                            type: annotation
                            prefix: Gedmo\Tree\Entity
                            dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                            alias: GedmoTree # (optional) it will default to the name set for the mapping
                            is_bundle: false

                  dql:
                        datetime_functions:
                            date: DoctrineExtensions\Query\Mysql\Date
                            date_format: DoctrineExtensions\Query\Mysql\DateFormat
                            dateadd: DoctrineExtensions\Query\Mysql\DateAdd
                            datesub: DoctrineExtensions\Query\Mysql\DateSub
                            datediff: DoctrineExtensions\Query\Mysql\DateDiff
                            day: DoctrineExtensions\Query\Mysql\Day
                            dayname: DoctrineExtensions\Query\Mysql\DayName
                            from_unixtime: DoctrineExtensions\Query\Mysql\FromUnixtime
                            last_day: DoctrineExtensions\Query\Mysql\LastDay
                            minute: DoctrineExtensions\Query\Mysql\Minute
                            second: DoctrineExtensions\Query\Mysql\Second
                            strtodate: DoctrineExtensions\Query\Mysql\StrToDate
                            time: DoctrineExtensions\Query\Mysql\Time
                            timestampadd: DoctrineExtensions\Query\Mysql\TimestampAdd
                            timestampdiff: DoctrineExtensions\Query\Mysql\TimestampDiff
                            week: DoctrineExtensions\Query\Mysql\Week
                            weekday: DoctrineExtensions\Query\Mysql\WeekDay
                            year: DoctrineExtensions\Query\Mysql\Year
                        numeric_functions:
                            acos: DoctrineExtensions\Query\Mysql\Acos
                            asin: DoctrineExtensions\Query\Mysql\Asin
                            atan2: DoctrineExtensions\Query\Mysql\Atan2
                            atan: DoctrineExtensions\Query\Mysql\Atan
                            ceil: DoctrineExtensions\Query\Mysql\Ceil
                            cos: DoctrineExtensions\Query\Mysql\Cos
                            cot: DoctrineExtensions\Query\Mysql\Cot
                            floor: DoctrineExtensions\Query\Mysql\Floor
                            hour: DoctrineExtensions\Query\Mysql\Hour
                            pi: DoctrineExtensions\Query\Mysql\Pi
                            power: DoctrineExtensions\Query\Mysql\Power
                            quarter: DoctrineExtensions\Query\Mysql\Quarter
                            rand: DoctrineExtensions\Query\Mysql\Rand
                            round: DoctrineExtensions\Query\Mysql\Round
                            sin: DoctrineExtensions\Query\Mysql\Sin
                            std: DoctrineExtensions\Query\Mysql\Std
                            tan: DoctrineExtensions\Query\Mysql\Tan
                        string_functions:
                            ascii: DoctrineExtensions\Query\Mysql\Ascii
                            binary: DoctrineExtensions\Query\Mysql\Binary
                            char_length: DoctrineExtensions\Query\Mysql\CharLength
                            concat_ws: DoctrineExtensions\Query\Mysql\ConcatWs
                            countif: DoctrineExtensions\Query\Mysql\CountIf
                            crc32: DoctrineExtensions\Query\Mysql\Crc32
                            degrees: DoctrineExtensions\Query\Mysql\Degrees
                            field: DoctrineExtensions\Query\Mysql\Field
                            find_in_set: DoctrineExtensions\Query\Mysql\FindInSet
                            group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
                            ifelse: DoctrineExtensions\Query\Mysql\IfElse
                            ifnull: DoctrineExtensions\Query\Mysql\IfNull
                            least: DoctrineExtensions\Query\Mysql\Least
                            match_against: DoctrineExtensions\Query\Mysql\MatchAgainst
                            md5: DoctrineExtensions\Query\Mysql\Md5
                            month: DoctrineExtensions\Query\Mysql\Month
                            monthname: DoctrineExtensions\Query\Mysql\MonthName
                            nullif: DoctrineExtensions\Query\Mysql\NullIf
                            radians: DoctrineExtensions\Query\Mysql\Radians
                            regexp: DoctrineExtensions\Query\Mysql\Regexp
                            replace: DoctrineExtensions\Query\Mysql\Replace
                            sha1: DoctrineExtensions\Query\Mysql\Sha1
                            sha2: DoctrineExtensions\Query\Mysql\Sha2
                            soundex: DoctrineExtensions\Query\Mysql\Soundex
                            substring_index: DoctrineExtensions\Query\Mysql\SubstringIndex
                            uuid_short: DoctrineExtensions\Query\Mysql\UuidShort
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%" # different ports are available, see SES console
    encryption: "%mailer_encryption%" # TLS encryption is required
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User


stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            sluggable: true












