app:
    resource: "@AppBundle/Resources/config/routing.yml"
    type: rest
    prefix:   /api

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

sonata_api_media:
    type:         rest
    prefix:       /api
    resource:     "@SonataMediaBundle/Resources/config/routing/api.xml"

user_public:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
