sonata_admin:
    options:
        use_select2:    false # disable select2
    templates:
        dashboard:                      AppBundle:SonataAdmin/Core:dashboard.html.twig
        layout:                         AppBundle:SonataAdmin:standard_layout.html.twig
    title:      ClaimEx
#    dashboard:
#        groups:
#                      Companies:
#                          on_top:               true
#                          label:                ~
#                          label_catalogue:      ~
#                          items:
#                              - admin.company

#    title_logo: bundles/app/images/fancy_acme_logo.png

    admin_services:
#        admin.claim:
#            route_generator: app.admin.route.generator
#        admin.position:
#            route_generator: app.admin.route.generator
