app_user_space:
    resource: "@AppBundle/Resources/config/routing/user/space/routing.yml"
    prefix:   /space

app_user_user_control:
    resource: "@AppBundle/Resources/config/routing/user/user_control/routing.yml"
    prefix:   /user-control

app_user_host_control:
    resource: "@AppBundle/Resources/config/routing/user/host_control/routing.yml"
    prefix:   /host-control

app_user_booking:
    resource: "@AppBundle/Resources/config/routing/user/booking/routing.yml"
    prefix:   /booking

