app_user_space_create:
    path: /create/step-{step}/{space}
    defaults: { _controller: AppBundle:User/Space/Mgmt/SpaceManipulation:step,space: 0}

app_user_space_upload_image:
    path: /upload-image/{space}
    defaults: { _controller: AppBundle:User/Space/Api/SpaceApi:spaceImage}

app_user_space_list:
    path: /list
    defaults: { _controller: AppBundle:User/Space/Mgmt/SpaceRetrieval:list}
app_user_space_view:
    path: /view/{space}
    defaults: { _controller: AppBundle:User/Space/Mgmt/SpaceRetrieval:view}

app_user_space_update:
    path: /update/{space}
    defaults: { _controller: AppBundle:User/Space/Mgmt/SpaceManipulation:update}