app_user_user_control_profile:
    path: /profile
    defaults: { _controller: AppBundle:User/UserControl/Mgmt/UserControlManipulation:profile}

app_user_user_control_setting:
    path: /setting
    defaults: { _controller: AppBundle:User/UserControl/Mgmt/UserControlManipulation:setting}

app_user_user_control_list_booking:
    path: /list-booking
    defaults: { _controller: AppBundle:User/UserControl/Mgmt/UserControlRetrieval:listBooking}

app_user_user_control_review_space:
    path: /review-space/{booking}
    defaults: { _controller: AppBundle:User/UserControl/Mgmt/UserControlManipulation:reviewSpace}

app_user_user_control_send_verified_code:
    path: /send-code-verify-phone-number
    defaults: { _controller: AppBundle:User/UserControl/Api/UserControlApi:sendVerifiedCode}

app_user_user_control_verify_code:
    path: /verify-phone-number
    defaults: { _controller: AppBundle:User/UserControl/Api/UserControlApi:verifyCode}

app_user_user_control_verification:
    path: /verification
    defaults: { _controller: AppBundle:User/UserControl/Mgmt/UserControlManipulation:verification}

app_user_user_control_list_inbox:
    path: /list-inbox
    defaults: { _controller: AppBundle:User/UserControl/Mgmt/UserControlRetrieval:listInbox}

app_user_user_control_reply_inbox:
    path: /reply-inbox/user-from/{user}/{messageInbox}
    defaults: { _controller: AppBundle:User/UserControl/Mgmt/UserControlManipulation:replyInbox}

app_user_user_control_wishlist:
    path: /wishlist
    defaults: { _controller: AppBundle:User/UserControl/Mgmt/UserControlRetrieval:wishlist}

app_user_user_control_remove_wishlist:
    path: /remove-wishlist/{space}/{userWishlist}
    defaults: { _controller: AppBundle:User/UserControl/Mgmt/UserControlManipulation:removeFromWishlist}