services:
    admin.user_fos:
            class: AppBundle\Admin\UserAdmin
            arguments: [~, AppBundle\Entity\Core\User, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Users }
