app_default:
    path: /
    defaults: { _controller: AppBundle:Default:index}


app_user:
    resource: "@AppBundle/Resources/config/routing/user/routing.yml"
    prefix:   /user

app_front:
    resource: "@AppBundle/Resources/config/routing/front/routing.yml"
    prefix:   /front

