app_switch_user:
    path: /switch-user
    defaults: { _controller: AppBundle:SwitchUser:index}

app_api_gettaxamount:
    path: /admin/app/get-tax-amount
    defaults: { _controller: AppBundle:Api:getTaxAmount}

