app_switch_user:
    path: /switch-user
    defaults: { _controller: AppBundle:SwitchUser:index}
app_test_notify:
    path: /test
    defaults: { _controller: AppBundle:SwitchUser:test}

app_api_gettaxamount:
    path: /admin/app/get-tax-amount
    defaults: { _controller: AppBundle:Api:getTaxAmount}

app_api_getclaimamountconverted:
    path: /admin/app/get-claim-amount-converted
    defaults: { _controller: AppBundle:Api:getClaimAmountConverted}

app_api_gettaxamountconverted:
    path: /admin/app/get-tax-amount-converted
    defaults: { _controller: AppBundle:Api:getTaxAmountConverted}

