imports:
#    - { resource: "services/accounting/payroll.yml" }


services:
    app.media.retriever:
        class: AppBundle\Services\Core\MediaRetriever
        calls:
            - [setContainer,["@service_container"]]
    app.claim_rule:
        class: AppBundle\Services\Core\ClaimRule
        calls:
            - [setContainer,["@service_container"]]
    app.util:
        class: AppBundle\Services\Core\Util
    app.api_authenticator:
        class: AppBundle\Security\ApiAuthenticator
        arguments: ['@doctrine.orm.entity_manager','@service_container']

    app.twig_extension:
            class: AppBundle\Twig\TwigExtension
            arguments: ["@service_container"]
            public: false
            tags:
                - { name: twig.extension }
    app.security.authentication_handler:
            class: AppBundle\Handler\AuthenticationHandler
            public: false
            arguments: ['@security.http_utils','@service_container','@security.token_storage']

    app.admin.route.generator:
            class: AppBundle\Route\RouteGenerator
            arguments: ['@router','@app.admin.route.no_cache']
    app.admin.route.no_cache:
            class: AppBundle\Route\RoutesCache
            arguments: ['%kernel.cache_dir%/sonata/admin','%kernel.debug%']







