imports:
#    - { resource: "services/accounting/payroll.yml" }


services:
    app.media.retriever:
        class: AppBundle\Services\Core\MediaRetriever
        calls:
            - [setContainer,["@service_container"]]
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager']






