imports:
#    - { resource: "services/accounting/payroll.yml" }


services:
    #global service
    app.controller:
            class: AppBundle\Services\Core\ControllerService
            calls:
                 - [setContainer, ["@service_container"]]


    app.media.retriever:
        class: AppBundle\Services\Core\MediaRetriever
        calls:
            - [setContainer,["@service_container"]]
    app.form_serializer:
        class: AppBundle\Services\Core\FormErrorsSerializer






