#AppBundle\Entity\Category:
#    constraints:
#        - Callback: validate
#
AppBundle\Entity\Checker:
    constraints:
        - Callback: validate
AppBundle\Entity\ApprovalAmountPolicies:
    constraints:
        - Callback: validate

AppBundle\Entity\Claim:
    constraints:
        - Callback: validate
AppBundle\Entity\ClaimType:
    constraints:
        - Callback: validate

AppBundle\Entity\Position:
    constraints:
        - Callback: validate

AppBundle\Entity\TaxRate:
    constraints:
        - Callback: validate

AppBundle\Entity\CurrencyExchange:
    constraints:
        - Callback: validate
