#AppBundle\Entity\Core\Message\Message:
#    properties:
#        sender:
#            - NotBlank:
#        recipient:
#            - NotBlank:

AppBundle\Entity\Core\Message\MessageType:
    properties:
        template:
            - NotBlank:
        type:
            - NotBlank: