#AppBundle\Entity\Core\Message\Message:
#    properties:
#        sender:
#            - NotBlank:
#        recipient:
#            - NotBlank:

AppBundle\Entity\Core\Location\Location:
    properties:
        geoLng:
            - NotBlank:
        geoLat:
            - NotBlank: